name: 'Firebase Live'

on:
  push:
    branches: ['develop']

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn && APP_UNSAFE_ALLOW_DYNAMIC_CONFIG=1 APP_INCLUDE_TEST_CONFIGS=1 yarn build
      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/641228848625/locations/global/workloadIdentityPools/github-action-pool/providers/github-token-provider'
          service_account: 'github-action-runner@refined-asset-359508.iam.gserviceaccount.com'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
#          repoToken: "${{ secrets.GITHUB_TOKEN }}"
#          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
