name: 'Firebase Live'

on:
  push:
    branches: ['develop']

jobs:
  deploy_live_website:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn && APP_UNSAFE_ALLOW_DYNAMIC_CONFIG=1 APP_INCLUDE_TEST_CONFIGS=1 yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
